events {}

http {
    upstream profile_service {
        server profile-service:8081;
    }
    upstream feed_service {
        server feed-service:8082;
    }

    server {
        listen 80;

        location /api/profile/ {
            proxy_pass http://profile_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/feed/ {
            proxy_pass http://feed_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}