version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: travel-postgres
    environment:
      POSTGRES_USER: travel
      POSTGRES_PASSWORD: travel123
      POSTGRES_DB: travel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - travel-network

  user-service:
    build: ./services/user-service
    container_name: travel-user-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: travel
      DB_PASSWORD: travel123
      DB_NAME: travel
    networks:
      - travel-network

  feed-service:
    build: ./services/feed-service
    container_name: travel-feed-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: travel
      DB_PASSWORD: travel123
      DB_NAME: travel
    networks:
      - travel-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: travel-jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true  # Поддержка протокола OTLP
    ports:
      - "16686:16686"  # Порт для UI Jaeger
      - "4317:4317"    # Порт для OTLP gRPC
      - "4318:4318"    # Порт для OTLP HTTP
    networks:
      - travel-network


  api-gateway:
    build: ./api-gateway
    container_name: travel-api-gateway
    ports:
      - "80:80"
    depends_on:
      - user-service
      - feed-service
    networks:
      - travel-network

networks:
  travel-network:
    driver: bridge

volumes:
  postgres_data: